export const FETCH_TOPICS_REQUEST = 'FETCH_TOPICS_REQUEST';
export const FETCH_TOPICS_SUCCESS = 'FETCH_TOPICS_SUCCESS';
export const FETCH_TOPICS_ERROR = 'FETCH_TOPICS_ERROR';

export const FETCH_ARTICLES_REQUEST = 'FETCH_ARTICLES_REQUEST';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_ERROR = 'FETCH_ARTICLES_ERROR';

export const VOTE_ARTICLE_REQUEST = 'VOTE_ARTICLE_REQUEST';
export const VOTE_ARTICLE_SUCCESS = 'VOTE_ARTICLE_SUCCESS';
export const VOTE_ARTICLE_ERROR = 'VOTE_ARTICLE_ERROR';

export const FETCH_COMMENTS_REQUEST = 'FETCH_COMMENTS_REQUEST';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_ERROR = 'FETCH_COMMENTS_ERROR';

export const VOTE_COMMENTS_REQUEST = 'VOTE_COMMENTS_REQUEST';
export const VOTE_COMMENTS_SUCCESS = 'VOTE_COMMENTS_SUCCESS';
export const VOTE_COMMENTS_ERROR = 'VOTE_COMMENTS_ERROR';

export const POST_COMMENT_REQUEST = 'POST_COMMENT_REQUEST';
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS';
export const POST_COMMENT_ERROR = 'POST_COMMENT_ERROR';

export const FORM_CHANGE = 'FORM_CHANGE';